services:
  - type: worker
    name: tether-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BRSAPI_KEY
        sync: false
