name: Tether Price Alert

on:
  schedule:
    - cron: "0 0,3,6,9,12,15,18,21 * * *"    # ساعت‌های 00:00, 03:00, 06:00, ...
    - cron: "30 1,4,7,10,13,16,19,22 * * *"  # ساعت‌های 01:30, 04:30, 07:30, ...
  workflow_dispatch:          # امکان اجرای دستی برای تست

jobs:
  send-price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Send Tether price
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BRSAPI_KEY: ${{ secrets.BRSAPI_KEY }}
        run: python tether_price_bot.py
